# install Apache server
---
- hosts: Appserver
  vars:
    http_port: 80
    max_clients: 1
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure apache is running (and enable it at boot)
    service:
      name: httpd
      state: started
      enabled: yes
  - name : to create a user called ravish
    user: name=ravish shell=/bin/bash group=root
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
